### ISSUE TITLE
Admin list filter required?

### ISSUE THREAD

**Issue by ferencevanmunster** [f213/django-suit-daterange-filter#3]
Hi,

The SuitDateWidget seems to be required by default.

https://github.com/f213/django-suit-daterange-filter/blob/master/date_range_filter/filter.py#L19

don't think this should be, and if so it should be configurable by the django.conf.settings ?

**Comment by f213** [comment]
SuitDateWidget is shipped with django-suit, and django-suit is the major requirement of this project. This happened because i wanted to stay focused.

I think the next step is to determine if django-suit is installed and automatically fall back to stock django admin widgets if not.

**Comment by ferencevanmunster** [comment]
Sorry bit of confusion..
I made a pull request with the changes ...
https://github.com/f213/django-suit-daterange-filter/pull/4

**Comment by f213** [comment]
Thank you! I have released the new version with your changes right now.
